---
- name: Add ruby 2.2 repository
  apt_repository:
    repo: 'ppa:brightbox/ruby-ng'
    state: present

- name: Update apt cache.
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: Install ruby and rubygems.
  apt: "name={{ item }} state=present"
  with_items:
    - ruby2.2
    - ruby2.2-dev

